#!/usr/bin/env bash
#ping an IP address 5 times
#Address must be passed in argument
#if no arguments, display error msg

if [[ -z "$1" ]]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi